export const courseRank = {
  1: ['CS',
    'CM',
    'EC',
    'IM',
    'EM',
    'EE',
    'ME',
    'BY',
    'CE',
    'GI',
    'IE',
    'MA',
    'MN',
    'MI',
    'PT',
    'XM',
    'XC'],
  2: ['AP', 'LE', 'CR', 'TX', 'PP', 'PM', 'FS', 'CL', 'IS', 'CH', 'IB'],
  3: ['BP'],
  4: ['AT', 'EM', 'IM', 'EC', 'CM', 'CS', 'RP', 'PR', 'AU', 'AE', 'RA', 'EI'],
  5: ['EC', 'AM', 'CF', 'CS', 'IT', 'CE', 'CH', 'ME', 'EI', 'EE', 'CZ', 'MM'],
  1013: ['ME', 'XM', 'CS', 'IT', 'EC'],
  1014: ['IT', 'XC', 'CS', 'CE', 'EC'],
  1015: ['EE', 'ME', 'CS', 'EC'],
  1026: ['EC', 'CS', 'EE', 'ME'],
  1101: ['CS', 'AD', 'IT', 'EC', 'CE', 'EE', 'ME'],
  1106: ['EC', 'EE', 'TX', 'CS', 'IT', 'AE', 'CE'],
  1107: ['FD'],
  1110: ['CS', 'BT', 'MZ', 'EE', 'IT', 'AD', 'EC', 'ME'],
  1112: ['IT', 'CS', 'CB', 'AL', 'EC'],
  1113: ['AD', 'CB', 'CS', 'IT', 'EC', 'CD', 'EE', 'ME', 'CE'],
  1114: ['ME', 'EE', 'CE', 'CS', 'IT', 'AD', 'AM', 'EC', 'CB'],
  1115: ['EE', 'EC', 'AD', 'CS'],
  1116: ['CE', 'EE', 'ME', 'CS', 'EC'],
  1118: ['AD', 'IT', 'CB', 'EC', 'ME', 'BM', 'EE', 'CS'],
  1120: ['AD', 'EC', 'CS', 'IT', 'EI', 'EE', 'ME', 'AU', 'CE'],
  1121: ['CS'],
  1122: ['ME', 'CE', 'CH', 'BT', 'EC', 'AD', 'AM', 'IT', 'CS'],
  1123: ['MD', 'AE', 'CS', 'MU', 'AM', 'IT', 'SC', 'EC'],
  1124: ['MR'],
  1125: ['CS'],
  1126: ['AG', 'RM', 'SC', 'CS', 'AD', 'BM', 'EC'],
  1127: ['EE', 'CH', 'BT', 'AE', 'EC', 'IT', 'CS'],
  1128: ['EC', 'SC', 'CS', 'AD'],
  1133: ['CE', 'CS', 'ME', 'EC'],
  1137: ['AD', 'EC', 'CS', 'CE', 'EE', 'ME'],
  1140: ['CS', 'AD', 'IT', 'CB', 'ME', 'EC'],
  1149: ['ME', 'EE', 'EC', 'AD', 'IT', 'CS'],
  1150: ['BM', 'FD', 'AG'],
  1202: ['CS', 'IT', 'AD', 'ME', 'EE', 'EC'],
  1205: ['CS'],
  1207: ['ME', 'RM', 'IT', 'CS', 'AD', 'BM', 'AM', 'EC'],
  1209: ['CE', 'IT', 'CS'],
  1210: ['CB', 'EC', 'EE', 'ME', 'CS', 'IT', 'AD', 'AL'],
  1211: ['RM',
    'EE',
    'CD',
    'AL',
    'CB',
    'EC',
    'AD',
    'IT',
    'CS',
    'CE',
    'AU',
    'FD',
    'ME',
    'CH',
    'AE',
    'BT',
    'MZ',
    'BM'],
  1212: ['BM', 'EC', 'CS', 'EE', 'ME', 'PE'],
  1213: ['EC', 'EE', 'CS', 'IT', 'BM', 'CB'],
  1216: ['CE',
    'ME',
    'AG',
    'MD',
    'CH',
    'EE',
    'EI',
    'EC',
    'AL',
    'CI',
    'BM',
    'SC',
    'AD',
    'IT',
    'CS'],
  1217: ['EC', 'CS', 'FD', 'BT', 'BM', 'AD'],
  1218: ['BM', 'AD', 'CS', 'IT', 'PH', 'MZ', 'ME', 'EE', 'EC'],
  1219: ['EC',
    'EE',
    'BT',
    'CS',
    'IT',
    'AD',
    'ME',
    'MU',
    'CH',
    'MR',
    'AU',
    'CE'],
  1221: ['EC', 'MD', 'CS'],
  1222: ['ME', 'EE', 'EC', 'AE', 'CS', 'IT'],
  1225: ['EC', 'EE', 'ME', 'IT', 'CS', 'AD'],
  1226: ['CS', 'IT', 'ME', 'EE', 'EC'],
  1228: ['CS', 'IT', 'EC', 'BM'],
  1229: ['ME', 'CS', 'EC', 'EE'],
  1230: ['ME', 'EE', 'AE', 'EC', 'CS'],
  1232: ['EE', 'IT', 'CS'],
  1233: ['AD', 'IT', 'CS', 'ME', 'EC', 'EE'],
  1237: ['AD', 'MZ', 'EE', 'ME', 'IT', 'CS', 'EC'],
  1238: ['EE', 'ME', 'CS', 'AD', 'EC', 'BM'],
  1241: ['ME', 'EE', 'EC', 'AD', 'CS'],
  1243: ['IT', 'ME', 'SC', 'AD', 'CS', 'EC'],
  1301: ['AD', 'CB', 'CS', 'EC', 'ME', 'EE', 'CE', 'IT'],
  1303: ['CB', 'EC', 'CS', 'IT', 'AD', 'EE', 'BT', 'AG', 'ME'],
  1304: ['SC',
    'AU',
    'EE',
    'AD',
    'ME',
    'EC',
    'BM',
    'IT',
    'AM',
    'CE',
    'CS',
    'RM'],
  1306: ['ME', 'BT', 'EC', 'IT', 'AD', 'CS'],
  1307: ['EC', 'AM', 'SC', 'EE', 'BM', 'CS', 'AD', 'IT', 'CB'],
  1309: ['AD', 'IT', 'CS', 'ME', 'CE', 'EE', 'EC'],
  1310: ['IT', 'CB', 'CS', 'AD', 'EC', 'EE', 'ME'],
  1311: ['AU',
    'CE',
    'FT',
    'CS',
    'IT',
    'AD',
    'EC',
    'EE',
    'AO',
    'AE',
    'MZ',
    'ME'],
  1313: ['BM', 'EC', 'CS', 'ME'],
  1315: ['BM', 'ME', 'CH', 'CE', 'CS', 'IT', 'EC', 'EE'],
  1316: ['EE',
    'AO',
    'EC',
    'CS',
    'AD',
    'IT',
    'ME',
    'CE',
    'MZ',
    'MU',
    'BM',
    'CH'],
  1317: ['EC', 'AD', 'AL', 'CS', 'IT', 'BT', 'EI', 'EE', 'CH', 'CE', 'ME'],
  1318: ['CS', 'EC', 'IT'],
  1319: ['EC', 'AD', 'CS', 'IT'],
  1321: ['PA', 'MN'],
  1322: ['BM',
    'EC',
    'AD',
    'CS',
    'SC',
    'IT',
    'ME',
    'FD',
    'CE',
    'AG',
    'AE',
    'EE'],
  1324: ['SC', 'AD', 'CS', 'IT', 'CO', 'EC', 'EE', 'ME'],
  1325: ['EC', 'ME', 'CS', 'IT', 'AD'],
  1333: ['ME'],
  1335: ['EC'],
  1399: ['BM',
    'AM',
    'ME',
    'SC',
    'CE',
    'MZ',
    'CS',
    'EE',
    'CB',
    'AD',
    'EC',
    'IT'],
  1401: ['CS', 'EC', 'IT', 'EE', 'CE', 'CH', 'ME'],
  1402: ['ME', 'CS', 'EC', 'EE'],
  1405: ['ME', 'EE', 'EC', 'SC', 'AD', 'CS'],
  1407: ['EC', 'ME', 'MR', 'BM', 'CS'],
  1408: ['AL', 'AD', 'IT', 'CS', 'CE', 'ME', 'EE', 'EC'],
  1409: ['BM', 'BT', 'EC', 'AD', 'ME', 'CS', 'CE', 'RM', 'EE'],
  1411: ['CE', 'EE', 'ME', 'IT', 'BT', 'CS', 'BM', 'AE', 'CB', 'EC'],
  1412: ['ME', 'CE', 'EE', 'EC', 'CB', 'CS', 'IT', 'AD'],
  1413: ['AD', 'SC', 'ME', 'CS', 'EC', 'EE'],
  1414: ['EC', 'CS', 'IT', 'EE', 'CE', 'ME'],
  1416: ['AD', 'CS', 'BM', 'ME', 'PH'],
  1419: ['CS',
    'AM',
    'EE',
    'EI',
    'AD',
    'CI',
    'MU',
    'CE',
    'CB',
    'CJ',
    'IC',
    'ME',
    'EC',
    'IT'],
  1420: ['ME', 'AE', 'EC', 'AD', 'IT', 'CS'],
  1421: ['EE', 'ME', 'CE', 'CS', 'EC'],
  1422: ['EC', 'CY', 'IT', 'CS', 'AD', 'CE', 'AG', 'ME', 'MD', 'EI', 'EE'],
  1423: ['CS', 'EC'],
  1424: ['PE', 'RM', 'AD', 'EC', 'CB', 'CS', 'EE', 'ME'],
  1426: ['CS', 'ME', 'IT', 'EE', 'EC'],
  1427: ['FT', 'IT', 'CS', 'EC'],
  1428: ['CS'],
  1430: ['EE', 'CS', 'EC', 'CE', 'ME'],
  1431: ['EE', 'ME', 'IT', 'CS', 'EC'],
  1432: ['ME', 'CB', 'CO', 'AM', 'EC', 'AD', 'CS'],
  1434: ['AE', 'EC', 'CS', 'EE', 'AD', 'AU'],
  1436: ['CS', 'CE', 'AD', 'ME', 'EE', 'EC'],
  1437: ['AD', 'CS', 'IT', 'CE', 'EC', 'EE', 'ME'],
  1438: ['EE', 'CS'],
  1441: ['ME', 'CE', 'EC', 'EE', 'CS'],
  1442: ['SC', 'BM', 'AD', 'CS'],
  1444: ['CS'],
  1445: ['CS', 'EC', 'ME'],
  1449: ['ME', 'CS', 'AG', 'EC'],
  1450: ['ME', 'EE', 'EC', 'IT', 'CS'],
  1452: ['CE', 'EE', 'ME', 'AD', 'CS', 'EC'],
  1501: ['EC', 'CS', 'IT', 'ME', 'EE', 'CE'],
  1503: ['BT', 'CE', 'IT', 'CS'],
  1504: ['CE', 'CH', 'ME', 'IT', 'CS', 'AD', 'SC', 'EC', 'EE', 'BT'],
  1505: ['ME', 'EE', 'EC', 'AD', 'CS', 'IT'],
  1507: ['AD', 'EC', 'EE', 'CS', 'IT'],
  1509: ['EC', 'IT', 'CS', 'ME', 'EI', 'EE', 'CE'],
  1510: ['EC', 'CS', 'CE', 'EE', 'ME'],
  1511: ['EE', 'CS'],
  1512: ['EC', 'CS', 'IT'],
  1513: ['CE', 'EE', 'ME', 'IT', 'CS', 'EC'],
  1516: ['EC', 'CS', 'CE', 'ME', 'EE'],
  1517: ['IT', 'CE', 'CS', 'EC', 'EE', 'ME'],
  1518: ['EE', 'ME', 'CS', 'IT', 'AE', 'EC'],
  1519: ['CS', 'IT', 'ME', 'CE', 'EE', 'EC'],
  1520: ['CB', 'EC', 'ME', 'CS', 'IT', 'AD'],
  1523: ['EE', 'CS', 'IT', 'ME', 'AU', 'EC'],
  1524: ['CS', 'EC', 'EE'],
  1525: ['EE', 'ME', 'CS', 'CE', 'EC'],
  1526: ['EC', 'CS'],
  1529: ['EC'],
  1533: ['CS', 'AD', 'IT'],
  1605: ['CS', 'IT', 'EC', 'EE'],
  2005: ['IB', 'CE', 'PR', 'CS', 'EC', 'IT', 'EE', 'EI', 'ME'],
  2006: ['TT',
    'TX',
    'FY',
    'PS',
    'MY',
    'AS',
    'MS',
    'PN',
    'MT',
    'PR',
    'CN',
    'MF',
    'ES',
    'IY',
    'BY',
    'BS',
    'CE',
    'ME',
    'RA',
    'EE',
    'CG',
    'EM',
    'IM',
    'EC',
    'CM'],
  2007: ['EY',
    'CH',
    'ME',
    'CL',
    'MF',
    'CE',
    'CN',
    'CS',
    'CM',
    'IM',
    'EC',
    'AT',
    'EM',
    'EE'],
  2025: ['AD', 'EE', 'ME', 'EC', 'CS'],
  2302: ['AD', 'CS', 'IT', 'EC', 'BM', 'AG', 'ME'],
  2314: ['CS', 'AG', 'AD', 'EE', 'EC'],
  2327: ['ME', 'EE', 'CE', 'EC', 'CS'],
  2328: ['EC', 'EE', 'BM', 'ME', 'CS', 'IT', 'SC'],
  2329: ['AD', 'CS', 'IT', 'EC', 'ME', 'XS', 'AG', 'BT', 'BM'],
  2338: ['BM', 'EE', 'CS', 'AG', 'AD', 'ME'],
  2341: ['EE', 'ME', 'IT', 'EC', 'BM', 'AD', 'CS', 'CE'],
  2342: ['ME', 'CE', 'EE', 'EC', 'CS'],
  2343: ['HT'],
  2345: ['EC', 'IT', 'CE', 'AD', 'ME', 'EE', 'CS', 'AG'],
  2346: ['AD', 'CE', 'CS', 'EC', 'EE', 'ME'],
  2347: ['IT', 'EE', 'AG', 'CS', 'ME', 'EC'],
  2349: ['FD', 'AD', 'RM', 'BM', 'CS'],
  2354: ['EC', 'EE', 'ME', 'CS', 'CE'],
  2356: ['CS', 'EC'],
  2357: ['EC', 'AD', 'IT', 'CS', 'EE', 'AG', 'ME', 'CE'],
  2360: ['MZ', 'ME', 'CS', 'AD', 'EC'],
  2367: ['CB', 'AD', 'CS', 'EC'],
  2369: ['EE', 'CE', 'ME', 'CS', 'EC'],
  2377: ['EC', 'AD', 'CS', 'CE', 'ME', 'EE', 'CB'],
  2601: ['EC', 'BT', 'EE', 'CS', 'IT', 'AE', 'BM', 'CE', 'CH', 'ME'],
  2602: ['EC', 'MD', 'ME', 'IT', 'CS', 'AD', 'AG'],
  2603: ['ME', 'EE', 'EC', 'CS'],
  2606: ['AE', 'CS', 'CE', 'ME', 'EC', 'EE'],
  2607: ['EC',
    'AM',
    'CB',
    'AD',
    'IT',
    'CS',
    'TX',
    'ME',
    'MZ',
    'CE',
    'FD',
    'BT',
    'EE'],
  2608: ['AD', 'EC', 'CS', 'IT', 'AL', 'CB', 'EE', 'ME', 'CE'],
  2609: ['AO',
    'CH',
    'EE',
    'PH',
    'IT',
    'AD',
    'CS',
    'EC',
    'CY',
    'FD',
    'AE',
    'AG',
    'ME',
    'CE'],
  2610: ['BT', 'ME', 'EE', 'BM', 'MZ', 'AD', 'CE', 'SC', 'EC', 'IT', 'CS'],
  2611: ['MC',
    'FD',
    'BT',
    'ME',
    'AE',
    'CH',
    'RM',
    'CE',
    'PH',
    'SF',
    'IT',
    'CS',
    'AM',
    'CI',
    'CY',
    'EE',
    'BM',
    'EC',
    'AG'],
  2612: ['CS', 'EE', 'EC', 'ME'],
  2613: ['EC', 'EE', 'CS', 'IT', 'SF', 'ME', 'CE', 'AU'],
  2614: ['EE', 'PC', 'TC', 'IT', 'CS', 'TX', 'EC'],
  2615: ['CE', 'MT', 'ME', 'EE', 'EC', 'CS'],
  2617: ['EE', 'MD', 'CE', 'ME', 'RM', 'IT', 'AD', 'CS', 'SC', 'EC'],
  2618: ['CD',
    'AM',
    'AD',
    'EC',
    'IT',
    'CS',
    'ME',
    'CE',
    'FT',
    'MZ',
    'BM',
    'EE'],
  2620: ['BT', 'EE', 'BM', 'CS', 'EC', 'IT', 'TS'],
  2621: ['ME', 'AE', 'MZ', 'IT', 'AD', 'CS', 'EC', 'CB', 'CE', 'EE'],
  2622: ['ME',
    'BT',
    'BM',
    'CE',
    'CH',
    'EE',
    'CO',
    'CB',
    'EC',
    'AD',
    'IT',
    'CS'],
  2623: ['EE', 'CS', 'EC', 'ME', 'IT', 'AD', 'BM'],
  2624: ['CS',
    'PH',
    'EC',
    'AG',
    'EE',
    'BT',
    'CH',
    'FD',
    'ME',
    'BM',
    'IT',
    'AD'],
  2625: ['AG', 'BM', 'EC', 'IT', 'AD', 'CS', 'CE', 'CH', 'EE', 'ME'],
  2627: ['BT', 'CE', 'BM', 'EE', 'EC', 'IT', 'CS', 'ME'],
  2628: ['ME', 'AU', 'BM', 'EE', 'AD', 'AM', 'SC', 'CS'],
  2630: ['EC', 'EE', 'ME', 'CS', 'AD'],
  2632: ['AM', 'EC', 'CS', 'IT', 'CE', 'ME', 'EE', 'BM'],
  2633: ['CS', 'EC', 'ME'],
  2634: ['SF',
    'CE',
    'ME',
    'PC',
    'EC',
    'EE',
    'CB',
    'AD',
    'BM',
    'AE',
    'CS',
    'FD',
    'AG',
    'IT'],
  2635: ['AD', 'CS', 'BM', 'EE', 'ME', 'EC'],
  2636: ['CS', 'EC', 'ME', 'CE', 'EE', 'AD', 'BM'],
  2638: ['IT', 'EC', 'CS'],
  2639: ['CS', 'AD', 'IT', 'EC', 'EE', 'ME'],
  2640: ['EE', 'ME', 'EC', 'CS', 'AD', 'CE'],
  2641: ['ME', 'EE', 'EC', 'CS', 'CE', 'AD', 'IT'],
  2642: ['IT', 'CE', 'ME', 'BM', 'AD', 'EE', 'CS', 'EC'],
  2643: ['CS', 'AD', 'EC', 'EE'],
  2646: ['AD', 'EE', 'EC', 'ME', 'CS', 'CE'],
  2647: ['IT', 'ME', 'CS', 'EC', 'EE'],
  2648: ['ME', 'CE', 'AU', 'EE', 'EC', 'CS'],
  2650: ['EE', 'EC', 'ME', 'AD', 'CS'],
  2651: ['CS', 'EE', 'AD', 'EC', 'CE', 'FT', 'ME'],
  2652: ['AD', 'CS', 'IT', 'EC', 'EE', 'ME'],
  2653: ['CE', 'ME', 'CS', 'IT', 'AD', 'CB', 'EC', 'EE'],
  2656: ['ME', 'EE', 'CE', 'EC', 'CS', 'AD'],
  2658: ['CE', 'EE', 'ME', 'EC', 'CS'],
  2659: ['EE', 'EC', 'BT', 'AD', 'CE', 'ME', 'CS', 'BM', 'IT'],
  2661: ['CS', 'AG', 'CE', 'IT', 'EC'],
  2665: ['ME', 'CS', 'CE', 'AE'],
  2673: ['ME', 'EE', 'CE', 'EC', 'CS'],
  2683: ['IT', 'BM', 'AG', 'EE', 'CS'],
  2702: ['SE',
    'EE',
    'CD',
    'CT',
    'AL',
    'EC',
    'CB',
    'AD',
    'IT',
    'CS',
    'TX',
    'FT',
    'CE',
    'FD',
    'AG',
    'BT',
    'MC',
    'ME',
    'BM',
    'EI'],
  2704: ['CS', 'EC', 'IT', 'AD', 'EE', 'MZ', 'CE', 'ME'],
  2705: ['CS', 'CE', 'EC', 'IT', 'ME'],
  2706: ['CE', 'AU', 'ME', 'EE', 'AM', 'EC', 'AD', 'SC', 'IT', 'CS'],
  2707: ['EI',
    'EE',
    'BM',
    'AG',
    'ME',
    'CH',
    'CE',
    'XM',
    'CS',
    'IT',
    'AD',
    'CD',
    'CJ',
    'RM',
    'EC'],
  2708: ['AG',
    'EE',
    'EI',
    'AL',
    'EC',
    'IT',
    'CS',
    'AU',
    'ME',
    'CE',
    'FD',
    'MZ',
    'AE',
    'CH',
    'BM'],
  2709: ['IT', 'EC', 'CS', 'EE', 'ME', 'CE', 'AU'],
  2710: ['ET', 'EE', 'ME', 'CE', 'CS', 'IT', 'AD', 'EC', 'CD', 'SC', 'TS'],
  2711: ['AL',
    'AD',
    'CS',
    'EI',
    'CE',
    'ME',
    'MZ',
    'CH',
    'IT',
    'EE',
    'CD',
    'FD',
    'AU',
    'EC'],
  2712: ['MZ',
    'ME',
    'AE',
    'CE',
    'AU',
    'FT',
    'TX',
    'CS',
    'IT',
    'AD',
    'EC',
    'EE',
    'EI',
    'BT'],
  2713: ['EC', 'CS', 'IT', 'ME', 'CE', 'EE'],
  2715: ['EC',
    'SC',
    'CI',
    'IT',
    'CS',
    'AD',
    'EE',
    'BM',
    'ME',
    'CH',
    'AG',
    'CE'],
  2716: ['EE', 'RM', 'TX', 'IT', 'CS', 'AE', 'AG', 'BM', 'EC'],
  2717: ['EC', 'CS', 'CE', 'AD'],
  2718: ['CE',
    'EE',
    'CJ',
    'MZ',
    'AD',
    'SC',
    'EC',
    'CS',
    'IT',
    'CD',
    'ME',
    'CB'],
  2719: ['EE',
    'CJ',
    'EC',
    'AD',
    'IT',
    'CS',
    'CE',
    'ME',
    'AE',
    'RM',
    'BM',
    'EI'],
  2721: ['EC', 'EE', 'CS', 'AD', 'ME', 'IC', 'AU', 'CE'],
  2722: ['EE', 'ME', 'CE', 'CS', 'AD', 'IT', 'EC', 'AM', 'SC', 'CI'],
  2723: ['CE', 'ME', 'MD', 'BM', 'EE', 'EC', 'AD', 'IT', 'CS'],
  2725: ['EC', 'EE', 'ME', 'CS', 'IT'],
  2726: ['AU',
    'AG',
    'AO',
    'BM',
    'CE',
    'FD',
    'EE',
    'CS',
    'EC',
    'AL',
    'MZ',
    'ME',
    'IT'],
  2727: ['AL',
    'SC',
    'EC',
    'CS',
    'IT',
    'AD',
    'EE',
    'AG',
    'BT',
    'BM',
    'ME',
    'FD',
    'CE'],
  2729: ['EE', 'MZ', 'ME', 'CS', 'IT', 'AD', 'EC', 'CB', 'AE'],
  2731: ['PD', 'ME', 'EE', 'AD', 'EC', 'CS'],
  2732: ['CS', 'EC', 'IT'],
  2733: ['CE', 'FT', 'CS', 'ME', 'EE', 'EC'],
  2734: ['SB', 'EC', 'CD', 'IT', 'ME', 'TS', 'AD', 'EE', 'MO', 'CS'],
  2735: ['EE', 'ME', 'CS', 'IT', 'AD', 'EC'],
  2736: ['ME', 'CE', 'BM', 'EE', 'EC', 'CB', 'AD', 'IT', 'CS'],
  2737: ['CE', 'CS', 'IT', 'EC'],
  2739: ['AD', 'CO', 'IT', 'CS', 'ME', 'EE', 'CB', 'EC', 'AM'],
  2740: ['IT', 'CS', 'AD', 'EC', 'AE', 'ME', 'PH'],
  2741: ['ME', 'IT', 'EE', 'CS', 'AD', 'EC'],
  2743: ['CE', 'AG', 'ME', 'FD', 'EE', 'BM', 'EC', 'AD', 'CS', 'SC'],
  2744: ['EC', 'CE', 'ME', 'CS', 'IT', 'EE'],
  2745: ['AD', 'CS', 'ME', 'EE', 'EC'],
  2747: ['EC', 'CE', 'CS', 'EE', 'ME'],
  2748: ['EE', 'CS', 'CE', 'EC'],
  2749: ['ME', 'IT', 'CS', 'SC', 'AG', 'AD', 'EC'],
  2750: ['EE', 'AG', 'BM', 'AE', 'ME', 'CS', 'CB', 'AD', 'EC', 'BT'],
  2751: ['CS', 'AD', 'IT', 'ME', 'EC', 'CB'],
  2752: ['CS', 'IT', 'EC', 'EE'],
  2753: ['AG', 'BM', 'ME', 'IT', 'AD', 'CS', 'EC'],
  2755: ['CE', 'AG', 'FD', 'AE', 'CS', 'IT'],
  2758: ['AU', 'EC', 'EE', 'ME', 'CS', 'IT'],
  2761: ['AD', 'CS', 'IT', 'RM', 'EC', 'SC'],
  2762: ['AD', 'CS', 'ME', 'EC', 'CE'],
  2763: ['CE', 'MZ', 'ME', 'CB', 'CS', 'AD', 'EC'],
  2764: ['CH',
    'CE',
    'ME',
    'BM',
    'MZ',
    'EE',
    'CB',
    'AM',
    'EC',
    'AD',
    'IT',
    'CS'],
  2767: ['CS', 'IT', 'BM'],
  2768: ['EN', 'CS', 'EC', 'CE'],
  2769: ['EC', 'FD', 'AD', 'CS', 'CB', 'BC', 'CE', 'EE', 'ME', 'PD', 'PE'],
  2770: ['ME', 'CS', 'EC', 'EE'],
  2772: ['CB', 'AD', 'EC', 'ME', 'CS'],
  2776: ['CE', 'ME', 'AU', 'MZ', 'CS', 'AD', 'AG'],
  3011: ['PH',
    'EE',
    'BT',
    'EC',
    'IT',
    'CS',
    'XM',
    'XC',
    'AU',
    'ME',
    'PC',
    'CE'],
  3016: ['ME', 'EE', 'CE', 'XC', 'CS', 'EC'],
  3018: ['ME', 'XC', 'XM', 'CS', 'EC', 'CE', 'EE'],
  3019: ['XM', 'ME', 'CE', 'EE', 'EC', 'CS'],
  3021: ['CE', 'EE', 'ME', 'CS', 'EC'],
  3403: ['CS', 'EC'],
  3410: ['EC', 'CS', 'ME', 'EE', 'CE'],
  3425: ['ME', 'EE', 'AD', 'EC', 'CS', 'CE'],
  3454: ['ME', 'AG', 'BM', 'AD', 'CS'],
  3456: ['AG', 'EE', 'ME', 'CS', 'BM', 'EC'],
  3460: ['CS', 'EE'],
  3461: ['AD', 'CS', 'EC', 'EE', 'ME'],
  3462: ['EE', 'ME', 'CS', 'CE', 'EC'],
  3464: ['CS', 'EC', 'EE', 'ME', 'CE'],
  3465: ['EE', 'ME', 'CE', 'CS', 'EC'],
  3466: ['EC', 'CS', 'ME', 'EE'],
  3701: ['CS', 'AL', 'AD', 'EC', 'EE', 'ME', 'CE'],
  3760: ['ME', 'AG', 'AD', 'CS', 'EC'],
  3766: ['ME', 'CS'],
  3782: ['EE', 'EC', 'CS', 'ME'],
  3786: ['EC', 'AD', 'CS', 'BM', 'MZ', 'ME', 'EE', 'AE'],
  3795: ['CS', 'EC', 'AD', 'EE', 'CE', 'ME'],
  3801: ['CE', 'IC', 'ME', 'CS', 'IT', 'EC', 'EE'],
  3803: ['ME', 'CE', 'EE', 'CH', 'EC', 'IT', 'CS'],
  3804: ['AU', 'CE', 'EE', 'ME', 'CS', 'EC', 'AG', 'BM'],
  3805: ['RM',
    'EE',
    'AD',
    'CE',
    'AG',
    'EC',
    'AO',
    'CS',
    'ME',
    'PH',
    'IT',
    'CH',
    'BT',
    'FD',
    'BM',
    'AE'],
  3806: ['CS', 'CB', 'IT', 'AD', 'EC', 'EE', 'BM', 'ME', 'CE'],
  3807: ['EE', 'ME', 'CE', 'IT', 'SC', 'CS', 'AD', 'EC', 'AE'],
  3809: ['EE', 'CS'],
  3810: ['CE', 'CS', 'EE', 'EI', 'FD', 'ME', 'IT', 'AD', 'AG', 'EC', 'BM'],
  3811: ['EE', 'CS', 'EC', 'IT', 'ME', 'CE', 'BM', 'AD'],
  3812: ['EE', 'ME', 'EI', 'EC', 'CE', 'IT', 'CS', 'AD'],
  3813: ['CS', 'EC', 'IT'],
  3814: ['EC', 'AD', 'CS'],
  3815: ['EC', 'EE', 'ME', 'TX', 'IT', 'CS', 'BM', 'BT'],
  3817: ['BT', 'EC', 'CS', 'ME', 'CE', 'EE'],
  3819: ['AD', 'CB', 'EC', 'CS', 'IT', 'AM', 'EE', 'IC', 'ME', 'CE'],
  3820: ['MC', 'CS'],
  3821: ['ME', 'EE', 'EC', 'CE', 'AG', 'CS', 'BM'],
  3822: ['EE', 'CS'],
  3825: ['AD', 'CS', 'ME', 'EE', 'EC'],
  3826: ['AD', 'EC', 'IT', 'CS', 'AG', 'EE', 'BM', 'ME', 'CE'],
  3829: ['EE', 'CE', 'ME', 'IT', 'CS', 'EC', 'AD'],
  3830: ['EE', 'ME', 'CB', 'EC', 'AL', 'IT', 'AD', 'CS'],
  3831: ['EC', 'AG', 'EE', 'ME', 'IT', 'AD', 'CS'],
  3833: ['AE', 'EC', 'CS', 'ME', 'EE', 'CE'],
  3841: ['CS', 'AD', 'EC', 'ME', 'CE'],
  3843: ['EC', 'ME', 'CS', 'CE', 'EE'],
  3844: ['SC', 'EE', 'BM', 'AD', 'CS'],
  3845: ['ME', 'EE', 'EC', 'CS'],
  3846: ['CE', 'CB', 'AD', 'CS', 'RM', 'ME', 'EE', 'EC'],
  3848: ['CS', 'ME'],
  3849: ['EE', 'ME', 'CS', 'IT', 'CE', 'EC'],
  3850: ['CS', 'AD'],
  3852: ['EC', 'EE', 'CS', 'CE'],
  3854: ['ME', 'CS', 'EE'],
  3855: ['CS', 'EC', 'ME'],
  3857: ['EE', 'ME', 'CS', 'CE', 'EC'],
  3859: ['CS'],
  3860: ['EE', 'ME', 'CS', 'EC'],
  3905: ['EC', 'CS', 'CE', 'ME', 'EE'],
  3908: ['CS', 'EC', 'EE', 'CE', 'ME'],
  3918: ['EE', 'ME', 'EC', 'CS', 'CE'],
  3920: ['ME', 'EE', 'EC', 'CE', 'CS', 'AD'],
  3923: ['CS'],
  3926: ['EC', 'CS', 'ME', 'EE', 'CE'],
  4020: ['EC', 'CS', 'GI', 'ME'],
  4023: ['ME', 'XM', 'EC', 'CS', 'CE', 'EE', 'IT', 'XC'],
  4024: ['XM', 'XC', 'ME', 'EE', 'CE', 'EC'],
  4669: ['CS', 'CE', 'EE', 'EC', 'ME'],
  4670: ['BM', 'EC', 'CS', 'AG', 'CE', 'EE', 'ME'],
  4672: ['EC', 'CS', 'EE', 'ME', 'CE'],
  4675: ['ME', 'CS', 'EC', 'EE'],
  4676: ['ME', 'EC', 'CS', 'EE'],
  4677: ['EC', 'CS'],
  4678: ['AD', 'EC', 'IT', 'CS', 'ME', 'CE', 'EE', 'CB'],
  4680: ['EC', 'CS', 'EE', 'CE', 'ME'],
  4686: ['ME', 'CS', 'CE', 'EC'],
  4864: ['EE', 'CE', 'ME', 'EC', 'CS'],
  4917: ['ME',
    'CB',
    'BT',
    'EC',
    'IT',
    'AD',
    'EE',
    'CE',
    'AG',
    'CS',
    'BM',
    'CD',
    'AM'],
  4925: ['AD', 'PH'],
  4927: ['CE', 'CS', 'ME'],
  4928: ['CE', 'EE', 'CS', 'AD', 'EC', 'ME'],
  4929: ['ME', 'EE', 'CE', 'EC', 'CS'],
  4931: ['CS', 'CE', 'ME', 'EC', 'AD', 'EE'],
  4932: ['CS'],
  4933: ['EC', 'CS', 'EE', 'ME'],
  4934: ['EE', 'ME', 'CS', 'EC', 'BM'],
  4938: ['EE', 'CS', 'AG'],
  4941: ['EE', 'ME', 'CS', 'EC'],
  4943: ['CE', 'AE', 'CS', 'ME', 'EE', 'EC'],
  4944: ['CE', 'AD', 'IT', 'EE', 'EC', 'CS'],
  4946: ['EE', 'ME', 'CS', 'AD', 'CE', 'EC'],
  4948: ['FT', 'CS'],
  4949: ['EE', 'IN', 'ME', 'MZ', 'EC', 'CS', 'CE'],
  4952: ['CE', 'CS', 'EC', 'ME', 'IT', 'EE'],
  4953: ['IT', 'CE', 'CS', 'EC', 'EE', 'ME'],
  4954: ['CE', 'EC', 'EE', 'ME', 'IT', 'CS'],
  4955: ['CE', 'ME', 'EE', 'CB', 'AD', 'EC', 'IT', 'CS'],
  4956: ['IC', 'CS'],
  4957: ['IT', 'CS', 'ME', 'EC'],
  4959: ['IT', 'AD', 'CS', 'EC', 'MZ', 'EE', 'BT', 'CE', 'ME'],
  4960: ['BM', 'ME', 'CE', 'CS', 'AD', 'IT', 'EC', 'EE', 'BT'],
  4961: ['EE', 'ME', 'EC', 'CS'],
  4962: ['AD', 'EE', 'ME', 'CE', 'CS', 'IT', 'EC'],
  4964: ['EC', 'CE', 'AE', 'CS', 'MU', 'MR', 'ME', 'EE'],
  4965: ['EC', 'BT', 'CS', 'AD', 'BM', 'EE', 'ME', 'CE'],
  4966: ['EE', 'ME', 'AD', 'EC', 'CS', 'CE'],
  4967: ['ME', 'EE', 'CE', 'EC', 'CS'],
  4968: ['EC', 'CE', 'EE', 'AD', 'CS', 'ME'],
  4969: ['EC', 'CS', 'ME', 'CE', 'EE'],
  4970: ['EC', 'CS', 'CE', 'EE', 'ME'],
  4971: ['EE', 'CE', 'ME', 'CS', 'IT', 'EC', 'AD'],
  4972: ['ME', 'CE', 'EE', 'EC', 'CS', 'AD'],
  4974: ['EE', 'CE', 'ME', 'CS', 'EC'],
  4975: ['EE', 'ME', 'EC', 'CS', 'CE'],
  4976: ['AG', 'AE', 'CS', 'EC'],
  4977: ['ME', 'CS', 'EC', 'EE'],
  4978: ['SC', 'ME', 'EE', 'EC', 'CE', 'AM', 'AG', 'AE', 'BT', 'BM', 'CS'],
  4980: ['EE', 'CE', 'ME', 'CS', 'EC'],
  4981: ['AD', 'IT', 'CS', 'CE', 'ME', 'EE', 'EC'],
  4982: ['CE', 'EC', 'CS', 'ME'],
  4983: ['EC', 'ME', 'AG', 'CE', 'CS'],
  4984: ['ME', 'EC', 'IT', 'CS'],
  4989: ['IT', 'CE', 'EC', 'CS', 'AG'],
  4992: ['CS', 'IT', 'EC', 'ME', 'EE', 'CE', 'AU'],
  4993: ['CS', 'EC', 'IT', 'AD', 'BM', 'AG', 'EE', 'ME'],
  4994: ['EC', 'IT', 'EE', 'ME', 'CS', 'CE'],
  4995: ['EE', 'EC', 'AD', 'CS'],
  4996: ['EC', 'EE', 'ME', 'CS', 'CE'],
  4998: ['CS', 'EC'],
  4999: ['AD', 'CS', 'CE', 'EC', 'ME'],
  5008: ['ME',
    'CE',
    'MF',
    'CN',
    'CS',
    'EC',
    'CM',
    'IM',
    'EM',
    'CW',
    'EE',
    'EY',
    'MG'],
  5009: ['EE', 'ME', 'EC', 'CE', 'CS'],
  5010: ['EE', 'ME', 'CE', 'CS', 'EC'],
  5012: ['CC'],
  5017: ['CE', 'CS', 'EC', 'ME', 'XC'],
  5022: ['ME', 'XC', 'XM', 'CS', 'EC', 'EE', 'CE'],
  5502: ['CE', 'AG', 'ME', 'EE', 'EC', 'CS'],
  5530: ['EC', 'CE', 'CS', 'CB', 'AD', 'EE', 'ME'],
  5532: ['EC', 'CS', 'ME', 'CE', 'EE'],
  5533: ['CS', 'CE', 'EC', 'EE', 'ME'],
  5536: ['AG', 'EE', 'CS', 'EC', 'ME'],
  5703: ['ME', 'EE', 'CE', 'CS', 'EC', 'IT'],
  5720: ['CS'],
  5832: ['AD', 'IT', 'CE', 'CS', 'EE', 'ME', 'EC'],
  5842: ['EC'],
  5851: ['CS'],
  5862: ['AE', 'BM', 'AG', 'CS'],
  5865: ['AD', 'EE', 'CE', 'ME', 'CS', 'EC', 'IT'],
  5901: ['EC', 'CS', 'ME', 'CE', 'EE'],
  5902: ['EC', 'EE', 'CS', 'IT', 'CE', 'AD', 'ME'],
  5904: ['EC', 'EE', 'ME', 'CS', 'SC', 'IT', 'AD'],
  5907: ['CE',
    'ME',
    'EC',
    'AD',
    'AE',
    'EE',
    'CH',
    'CB',
    'AG',
    'IT',
    'CS',
    'MR'],
  5910: ['CB', 'EE', 'BM', 'ME', 'CE', 'CS', 'IT', 'AD', 'EC'],
  5911: ['EC', 'CS', 'ME', 'EE'],
  5912: ['AD', 'IT', 'EC', 'EE', 'CS', 'CE', 'ME'],
  5913: ['CE', 'PD', 'EC', 'TX', 'ME', 'CS', 'EE'],
  5914: ['ME', 'EE', 'CE', 'CB', 'AD', 'EC', 'CS'],
  5915: ['CE', 'EE', 'ME', 'CS', 'EC'],
  5919: ['EC', 'BT', 'CS', 'ME', 'CH', 'EE'],
  5921: ['AD', 'CB', 'CS', 'EC', 'CE', 'EE', 'ME'],
  5924: ['ME', 'EC'],
  5930: ['CS', 'CE', 'ME', 'EE', 'EC'],
  5935: ['AU', 'CE', 'ME', 'CS', 'EC', 'EE'],
  5942: ['IT', 'CS', 'EE', 'EC', 'CE'],
  5986: ['IT', 'EC', 'CS', 'EE', 'ME', 'CE'],
  5988: ['EE', 'ME', 'CS', 'EC', 'CE'],
  5990: ['ME', 'EE', 'EC', 'CE', 'CS']
}